@startuml
!pragma layout smetana

object Chill
object User
object SeeLater
object Seen
object Media
object Movie
object Show
object Season
object Episode
object Search
object Login

Chill *-- User

Chill *-- Media
User *-- SeeLater
User *-- Seen

Media <|-- Movie
Media <|-- Show
Show *-- Season
Season *-- Episode

Chill *-- Search
Chill *-- Login

@enduml
