@startuml
!pragma layout smetana

object Chill
object User
object SeeLater
object Seen
object Media
object Movie
object Show
object Season
object Episode

Chill *-- Media
User *-- SeeLater
User *-- Seen
User *-- Media

Media <|-- Movie
Media <|-- Show
Show *-- Season
Season *-- Episode

Chill *-- User


@enduml
